inter.broker.listener.name=PLAINTEXT_DOCKER
process.roles=broker,controller
controller.listener.names=CONTROLLER
delete.topic.enable=true
controller.quorum.voters=1@kafka:9093
auto.create.topics.enable=true
node.id=1
advertised.listeners=PLAINTEXT_DOCKER://kafka:9092,PLAINTEXT_HOST://localhost:29092
listener.security.protocol.map=PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
listeners=PLAINTEXT_DOCKER://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
zookeeper.connect=
log.dirs=/var/lib/kafka/data
offsets.topic.replication.factor=1
